deploy to dev.toycode.org:
  script:
  - "npm install"
  - "bower install"
  - "forever stop kidscoding || true"
  - "forever start --uid \"kidscoding\" -a ./node_modules/.bin/gulp"
  type: deploy
  tags:
  only:
  - master
