toycode.org:
  script:
  - "npm install --production"
  - "bower install --production"
  - "./node_modules/.bin/gulp appcache"
  - "forever stop kidscoding || true"
  - "forever start --uid \"kidscoding\" -a index.js --url=http://toycode.org"
  type: deploy
  tags:
  - production
  only:
  - master

dev.toycode.org:
  script:
  - "npm install --production"
  - "bower install --production"
  - "./node_modules/.bin/gulp appcache"
  - "forever stop kidscoding || true"
  - "forever start --uid \"kidscoding\" -a index.js --url=http://dev.toycode.org"
  type: deploy
  tags:
  - dev
  only:
  - master
