deploy to dev.toycode.org:
  script:
  - "npm install"
  - "bower install"
  - "./node_modules/.bin/gulp appcache"
  - "forever stop kidscoding || true"
  - "forever start --uid \"kidscoding\" -a -c \"node --harmony\" app.js"
  type: deploy
  tags:
  only:
  - master
